# Use visual studio default settings
set(ARCH_TYPE WIN)
if(MSVC)
	unset(CMAKE_C_FLAGS)
	unset(CMAKE_C_FLAGS_DEBUG)
	unset(CMAKE_C_FLAGS_RELEASE)
	unset(CMAKE_CXX_FLAGS)
	unset(CMAKE_CXX_FLAGS_DEBUG)
	unset(CMAKE_CXX_FLAGS_RELEASE)
endif()
